export const blogs=[
    {
        id:1,
        title:'BLACK MARBLE',
        thumbnail:'/t1.png',
        text:"Black in interior design is another type of color with a special mystery and charm. Even if it’s an attempt to create a traditional old-fashioned atmosphere or design based on a sweet concept. Using black as the basis and black line waves as a moving pattern on different types of marble rock floors allows us to create unlimited unique and unique spaces. Marquina Spain is one of the most famous black marbles in the world. There is a dark black background and fine white mineral lines scattered throughout the rock floor. The density of the mineral strands varies from slab to stone. Saint Laurent, the black marble, reflects Paris’ luxury and modernity. In haute couture from Yves Saint Laurent, founder of the famous fashion brand YSL, with a black and dark brown finish. Infused with luxurious white and gold strands The classic color combination of black and gold creates the most classic aesthetic, which is widely popular in Modern and Contemporary styles."
    },
    {
        id:2,
        title:'THE POWER OF TEXTURAL CONTRASTS WITH CARL HANSEN & SØN’S ‘PK1’ CHAIR IN PAPER CORD ',
        thumbnail:'/t2.png',
        text:"For me, the way a space feels is just as important as the way it looks. And one of the key factors in creating a cosy, welcoming and beautiful home is texture – specifically, elements of textural contrast. Mixing soft materials with hard, matte surfaces with glossy or rough textures with smooth gives any interior an instant lift, adding interest in a way that appeals to multiple senses. It’s particularly important with minimalist decor, which if not done carefully can end up appearing flat and lifeless rather than calm and uncluttered.  It really doesn’t take much to add a touch of textural contrast to a room, and often a single well-chosen piece is all you need. Step forward the gorgeous ‘PK1’ chair by Danish Modernist architect and designer Poul Kjærholm (1929-1980), which pairs a sleek stainless-steel frame with a woven seat and backrest. Kjærholm created the ‘PK1’ in 1955 and it marked his first ever chair design. He had a penchant for steel and used it in much of his work, often combining it with organic materials to add softness and tactility to his pared-back pieces. His original version of the ‘PK1’ had a seat and backrest made from wicker, but Carl Hansen & Søn has now reimagined and relaunched it using FSC-certified paper cord – a durable and sustainable alternative which patinates beautifully over time. Paper cord is something of a signature element for Carl Hansen & Søn and takes a starring role in some of its most iconic pieces, including the likes of Hans J. Wegner’s ‘Wishbone’ chair and ‘CH25’ lounge chair. The all-in-one seat and backrest of the ‘PK1’ presented a challenge, however, and so the company worked closely with the Kjærholm family to develop a new and very intricate technique. It takes a skilled craftsperson 15 hours and 180m of cord to hand-weave a single ‘PK1’ chair, but the result is worth it – strong, flexible, and just as attractive from the back as it is from the front."
    },
    {
        id:3,
        title:'MINIMALIST FURNITURE FROM DINESEN & JOHN PAWSON',
        thumbnail:'/t3.png',
        text:"Happy 1st May! I’ll be publishing my normal start-of-the-month round-up of design news later this week, but first I want to share details of an exciting launch that merits a post of its very own: a collection of timeless, minimalist furniture from Danish flooring and wood specialist Dinesen and renowned British architect John Pawson.  The collection is a celebration of more than 30 years of collaboration, with Pawson first working with Dinesen in 1992 on a dining table, bench and stool for his London home, Pawson House. Spurred on by his belief that flooring is a crucial yet often-overlooked aspect of interior design, he took inspiration from the dimensions of Dinesen’s planks to create pieces that almost looked as if they were lifted from the floor beneath. The new collection includes the original three designs, along with a lounge chair, a lounge table, a sofa and a daybed. All are made from solid Douglas fir and showcase Pawson’s signature pared-back aesthetic, which draws on influences from Japan and the work of architect Shiro Kuramata. They also reflect the spirit of the Danish word umage, which refers to the dialogue between designer, material and maker and the marks this leaves on an object along the way. "
    }
]